const KARNATAKA_WARD_NAMES = [
  'SS Puram',
  'SIT Extension',
  'Kyathsandra',
  'Maralur',
  'Maralur Dinne',
  'Gubbi Gate',
  'Sira Gate',
  'Ashoka Road',
  'Vinoba Nagar',
  'Shanti Nagar',
  'Jayanagar',
  'Batawadi',
  'Belagumba',
  'Heggere',
  'Saraswathipuram',
  'Sadashivanagar',
  'Hanumanthapura',
  'Kuvempu Nagar',
  'Mahalakshmi Layout',
  'KHB Colony',
  'Tilak Park',
  'MG Road',
  'B.H. Road',
  'Amanikere',
  'University Road',
  'Ring Road',
  'Yallapura',
  'Devaraj Urs Layout',
  'Gandhi Nagar',
  'HMT Layout',
  'Kempegowda',
  'Chowdeshwari',
  'Attur',
  'Yelahanka Satellite Town',
  'Jakkur',
  'Thanisandra',
  'Byatarayanapura',
  'Kodigehalli',
  'Vidyaranyapura',
  'Dodda Bommasandra',
  'Kuvempunagar',
  'Shettihalli',
  'Mallasandra',
  'Bagalagunte',
  'T Dasarahalli',
  'Jalahalli',
  'J P Park',
  'Radhakrishna Temple',
  'Sanjay Nagar',
  'Ganganagar',
  'Hebbal',
  'Nagavara',
  'HBR Layout',
  'Horamavu',
  'Ramamurthy Nagar',
  'K R Puram',
  'Mahadevapura',
  'Varthur',
  'Bellandur',
  'Koramangala',
  'Ejipura',
  'Adugodi',
  'Lakkasandra',
  'Basavanagudi',
  'Hanumantha Nagar',
  'JP Nagar',
  'BTM Layout',
  'HSR Layout',
  'Bommanahalli',
  'Begur',
  'Electronic City',
  'Hongasandra',
  'Madiwala',
  'Bilekahalli',
  'Bannerghatta',
  'Uttarahalli',
  'Rajarajeshwari Nagar',
  'Nayandahalli',
  'Kengeri',
  'Nagarabhavi',
  'Vijayanagar',
  'Govindarajanagar',
  'Rajajinagar',
  'Basaveshwaranagar',
  'Malleshwaram',
  'Yeshwanthpur',
  'Mathikere',
  'Shivajinagar',
  'Vasanth Nagar',
  'Pulakeshinagar',
  'Ulsoor',
  'Domlur',
  'Indiranagar',
  'HAL Airport',
  'Marathahalli',
  'Whitefield',
  'Kadugodi',
  'Kamakshipalya',
  'Jagajeevanram Nagar',
  'Padarayanapura',
  'Chickpet',
  'Cottonpet',
  'Gandhinagar',
];

const normalizeText = (value) => String(value || '').toLowerCase().replace(/\s+/g, ' ').trim();

const inferWardName = (...values) => {
  const haystack = normalizeText(values.filter(Boolean).join(' '));
  if (!haystack) return undefined;

  return KARNATAKA_WARD_NAMES.find((name) => haystack.includes(normalizeText(name)));
};

module.exports = {
  KARNATAKA_WARD_NAMES,
  inferWardName,
};
